[package]
authors = ["Ted Mielczarek <ted@fullstory.com>"]
edition = "2018"
name = "shared-core"
version = "0.1.0"

[dependencies]
anyhow = "1.0.32"
futures = {version = "0.3.5", features = ["async-await", "thread-pool"]}
