[package]
authors = ["Ted Mielczarek <ted@fullstory.com>"]
edition = "2018"
name = "shared-android"
version = "0.1.0"

[dependencies]
shared-core = {path = "../shared-core"}
once_cell = "1.4.1"
futures-timer = "3.0.2"
